name: Laravel Develop CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP for Laravel
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo_mysql, zip, exif, pcntl, bcmath
          tools: composer:v2
          coverage: none

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      # Copy environment file
      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build Docker image with BuildX (without pushing)
      - name: Build Docker image with BuildX
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.repository }}:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max